  print("This is the way you are directed to use")
  print("If you don't have Lua setup read extra.md")
  print("To enjoy this project:-")
  print("1.) Downlaod or copy the Respiratory")
  print("2.) Run = Cargo run")
  print("3.) Enjoy just close the terminal to stop this.")
